### ISSUE TITLE
App background turns white on Dark Mode (MacOS Catalina)

### ISSUE THREAD

**Issue by LeoDoesThings** [henryefranks/pac-bar#14]
The background colour for the app turns white when using dark mode which makes the text basically unreadable.
(Running MacOS Catalina 10.15.4)

![image](https://user-images.githubusercontent.com/38830741/80304884-3f873780-880d-11ea-858a-2a0272f1b3fc.png)
![image](https://user-images.githubusercontent.com/38830741/80304875-2ed6c180-880d-11ea-9ed5-a8a9ad6cbc01.png)

**Comment by henryefranks** [comment]
Hi @LeoDoesThings, I can't seem to recreate that bug - perhaps I've fixed it without realising in a newer build. Hopefully the next release should put an end to that issue for certain, but just in case, make sure you're running the latest version (v1.2 at the time of writing).

**Comment by LeoDoesThings** [comment]
@henryefranks using v1.2 still happening on MacOS 10.15.6
![image](https://user-images.githubusercontent.com/38830741/91932643-d83d3f00-ed3a-11ea-8f1e-911ed6cb445b.png)

**Comment by henryefranks** [comment]
Ok, hopefully it'll be fixed in the next release.

**Comment by LeoDoesThings** [comment]
Thanks for fixing in v1.3. Also seems to be working perfectly fine on Big Sur.
